const L = require('/home/user/Wiederholung/plan/werkzeuge/pruefstand/lib.js');
const { start, neueSeite, aktion, GERAETE, vollerStore } = L;
(async () => {
  const P = n => '<img src=x onerror=xss(' + n + ')>';
  const store = vollerStore();
  const b1 = store['users/u1/bereiche/b1'];
  b1.name = P(1); b1.sets.s1.name = P(2); b1.sets.s4.name = P(3); b1.sets.s5.name = P(4);
  store['users/u1/bereiche/b2'].name = '"><svg onload=xss(5)>';
  const k0 = store['users/u1/karten/k0']; k0.wort = P(6); k0.uebersetzung = P(7); k0.extra = P(8);
  const k1 = store['users/u1/karten/k1']; k1.extra = 'https://a.b/x.png"onerror="xss(9)';
  const k2 = store['users/u1/karten/k2']; k2.extra = 'javascript:xss(10)';
  const k3 = store['users/u1/karten/k3']; k3.extra = 'https://a.b/"onmouseover="xss(11)';
  store['users/u1'].name = P(12);
  const b = await start();
  const { p } = await neueSeite(b, GERAETE.handy, { store, warte: 1800 });
  await p.evaluate(() => { window.__x = []; window.xss = n => window.__x.push(n); });
  const log = [];
  const schritt = async (name, fn) => { try { await fn(); log.push(name + ' ok'); } catch (e) { log.push(name + ' FEHLT: ' + e.message.slice(0, 80)); } };
  await schritt('lernen', async () => { await aktion(p, 'tab-lernen', null, 600); });
  await schritt('bereich-sheet', async () => { await aktion(p, 'bereich-sheet-auf', null, 600); await aktion(p, 'bereich-sheet-zu', null, 500); });
  await schritt('verwalten', async () => { await aktion(p, 'tab-verwalten', null, 700); });
  await schritt('sets', async () => { await aktion(p, 'toggle-sets', null, 500); });
  await schritt('set-open', async () => { await aktion(p, 'toggle-set-open', null, 500); });
  await schritt('detail', async () => { await aktion(p, 'card-detail', 'k0', 600); await aktion(p, 'card-detail-loeschen', null, 600); await aktion(p, 'dlg-cancel', null, 500); });
  await schritt('edit', async () => { await p.keyboard.press('Escape'); await aktion(p, 'tab-verwalten', null, 500); await aktion(p, 'edit-card', 'k0', 600).catch(()=>{}); await p.keyboard.press('Escape'); });
  await schritt('mehr', async () => { await aktion(p, 'bereich-mehr-auf', null, 600); await aktion(p, 'bereich-mehr-zu', null, 500); });
  await schritt('suche', async () => { await p.fill('#f-search', 'img'); await p.waitForTimeout(700); await aktion(p, 'search-scope', null, 700).catch(()=>{}); });
  await schritt('drill', async () => { await aktion(p, 'search-clear', null, 400); await aktion(p, 'open-drill', null, 600); await p.evaluate(() => { const r = document.querySelector('input[name=drill-mode][value=sets]'); if (r) { r.click(); } }); await p.waitForTimeout(500); await aktion(p, 'close-drill', null, 400); });
  await schritt('select+verschieben', async () => { await aktion(p, 'toggle-select-mode', null, 500); await aktion(p, 'toggle-card-select', 'k1', 300); await aktion(p, 'auswahl-verschieben', null, 600); await p.keyboard.press('Escape'); await p.waitForTimeout(300); await aktion(p, 'auswahl-speicherkarte', null, 600); await p.keyboard.press('Escape'); await p.waitForTimeout(300); await aktion(p, 'toggle-select-mode', null, 400); });
  await schritt('fortschritt', async () => { await aktion(p, 'tab-fortschritt', null, 800); });
  await schritt('einst', async () => { await aktion(p, 'einstellungen', null, 600); for (const s of ['kartensaetze', 'daten']) { await aktion(p, 'einst-seite', s, 600); await aktion(p, 'einstellungen', null, 500).catch(()=>{}); } });
  await schritt('lern-set', async () => { await aktion(p, 'einstellungen-zu', null, 400).catch(()=>{}); await aktion(p, 'tab-lernen', null, 600); await aktion(p, 'lern-set', null, 700); await aktion(p, 'lern-notiz', null, 400).catch(()=>{}); });
  await schritt('session', async () => { await aktion(p, 'tab-lernen', null, 500); await aktion(p, 'start-session', null, 800); for (let i = 0; i < 6; i++) { await aktion(p, 'reveal', null, 500).catch(()=>{}); await aktion(p, 'grade-known', null, 700).catch(()=>{}); } });
  // hover over all links to trigger onmouseover
  await p.evaluate(() => document.querySelectorAll('a').forEach(a => a.dispatchEvent(new MouseEvent('mouseover', { bubbles: true }))));
  const x = await p.evaluate(() => window.__x);
  const html = await p.evaluate(() => document.documentElement.outerHTML);
  console.log(log.join('\n'));
  console.log('XSS ausgeloest:', JSON.stringify(x));
  console.log('rohes <img src=x im DOM:', (html.match(/<img src="?x"? onerror/g) || []).length);
  console.log('Fehler:', p.fehler.join(' | ') || 'keine');
  await b.close();
})();
